# This is a basic workflow to help you get started with Actions

name: Deploy on push master branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v1
          with:
            node-version: '14.x'
        - name: Install Serverless Framework and Yarn
          run: npm install -g serverless yarn
        - name: Serverless AWS authentication
          run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - name: Install NPM dependencies
          run: yarn
        # Optional
        #- name: Build assets
        #  run: npm run assets-dev
        - name: Deploy Lambda functions
          run: sls deploy --verbose


